const RUS_DEFAULT_IMAGE_IDS = [
    'AgACAgIAAxkBAAIBgWVuHdYc3DV6_rdrpLtMJs_VpCj_AAKf0jEbnp9wS5mMoc5_Iur1AQADAgADbQADMwQ',
    'AgACAgIAAxkBAAIBgmVuHi0JX9L4HuTLRB6oZGwPioMpAAKi0jEbnp9wS8X0p2vYEwJ2AQADAgADbQADMwQ',
    'AgACAgIAAxkBAAIBg2VuHnNXKrZZoTydwlMxEbU7n9OWAAKl0jEbnp9wS3ULsaNFhsqSAQADAgADbQADMwQ',
    'AgACAgIAAxkBAAIBhGVuHrOzXeSfWx5de26_nWbtxlRlAAKm0jEbnp9wS0piHL9SZqzzAQADAgADbQADMwQ',
    'AgACAgIAAxkBAAIBiWVuIQLAfZDdXkpLi33TUlC1FHpAAAK10jEbnp9wS0BgdNKsA7seAQADAgADbQADMwQ',
    'AgACAgIAAxkBAAIBjGVuIzhkJk6o7v6VpE7tY1rgaMa5AAK60jEbnp9wS5_pcgNJxAssAQADAgADeAADMwQ',
    'AgACAgIAAxkBAAIBjWVuI83LId0imBcNAsh2Tj9QqBj_AAK_0jEbnp9wSzgE6ny-Yw4NAQADAgADbQADMwQ',
    'AgACAgIAAxkBAAIBjmVuI-Vm3rsRqm99UGQMGle3JUnJAALD0jEbnp9wS3FiEk4zeGwoAQADAgADbQADMwQ',
];

const ENG_DEFAULT_IMAGE_IDS = [
    'AgACAgIAAxkBAAIBf2VuHSafr1SkmMPmuczVmdPasiHuAAKY0jEbnp9wS9mZGrjDypCXAQADAgADbQADMwQ',
    'AgACAgIAAxkBAAIBhWVuH4jwB-7awEcgAzq8tzNpa1H0AAKs0jEbnp9wSzkCHcnUeLsYAQADAgADbQADMwQ',
    'AgACAgIAAxkBAAIBhmVuH_ezDoVRoh3Cz146iPlpKJvXAAKt0jEbnp9wS6VaRAi3wj1HAQADAgADbQADMwQ',
    'AgACAgIAAxkBAAIBh2VuIIRexc0fAsIzy7-DnPwbAAFFTAACs9IxG56fcEuL3RHyTcgYLwEAAwIAA20AAzME',
    'AgACAgIAAxkBAAIBimVuIV-td7LoL2vyirFp7o5k2ySBAAK20jEbnp9wSwR8dFdE_xk3AQADAgADbQADMwQ',
    'AgACAgIAAxkBAAIBi2VuIddWr70y0g5A7_OnCWt5a9lGAAK30jEbnp9wS6i4DHS-Qf6TAQADAgADbQADMwQ',
    'AgACAgIAAxkBAAIBj2VuJJ-EwGDUdCTlJR45UJBLo8uuAALE0jEbnp9wS5cvMRci6tglAQADAgADbQADMwQ',
    'AgACAgIAAxkBAAIBkGVuJVyV6-MbnWP8uwzui__BxT2EAALH0jEbnp9wS8UomJEFh0QjAQADAgADbQADMwQ',
    'AgACAgIAAxkBAAIBkWVuJrFDXPe7RSB3ugvc6R0tqyi_AALR0jEbnp9wS0RFMIey7GZ-AQADAgADbQADMwQ',
]

export const LANGUAGE_DEFAULT_IMAGE_IDS = {
    'rus': RUS_DEFAULT_IMAGE_IDS,
    'eng': ENG_DEFAULT_IMAGE_IDS,
}