name: Autorestart
run-name: Restart deploy on failure

on:
  workflow_run:
    workflows: [Deploy to Server]
    types: [completed]

jobs:
  on-success:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    environment: production
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Echo failed
        run: echo 'The triggering workflow failed'

      - name: Trigger workflow on failure
        uses: peter-evans/repository-dispatch@v2
        with:
#         don't forget to generate Personal Access Token
          token: ${{ secrets.PAT_SECRET }}
          repository: ${{ github.repository }}
          event-type: restart-event