on:
  workflow_run:
    workflows: [Deploy to Server]
    types: [completed]

jobs:
  on-success:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Echo failed
        run: echo 'The triggering workflow failed'

      - name: Trigger workflow on failure
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.YOUR_PAT_SECRET }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"main"}'

