name: Deploy to Server
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  deploy:
#    runs-on: windows-latest
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy to server
        run: npm run start

        env:
          NODE_ENV: production