name: Stop Service Workflow

on:
  workflow_dispatch:

jobs:
  stop-service:
    runs-on: self-hosted

    steps:
      - name: Stop Service
        run: |
          sc.exe STOP telegramocrbot.exe
          sc.exe DELETE telegramocrbot.exe
        continue-on-error: true